use super::ResolveMutation;
use crate::DataSource;
pub mod create_friend_mutation_input;
pub mod create_friend_mutation_payload;
pub mod friend;
pub mod friend_connection;
pub mod me;
pub mod mutation;
pub mod notification;
pub mod query;
pub mod search_result;
pub mod url;
pub mod user;
