name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --all --verbose
      - name: Run tests
        run: cargo test --all --verbose
      - name: Run clippy
        run: |
          cargo clippy -- \
          -D clippy::all \
          -D clippy::nursery \
          -W clippy::pedantic
